[package]
name = "blobatar-ui"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
blobatar-core = { path = "../blobatar-core" }
blobatar-export = { path = "../blobatar-export" }
blobatar-gpui = { path = "../blobatar-gpui" }
blobatar-wall = { path = "../blobatar-wall" }
unicode-segmentation = "1.12"
rand = "0.8"
serde.workspace = true
serde_json.workspace = true
